/**
 * Generic workspace support — company context comes from user-uploaded files,
 * not from hardcoded domain constants.
 */

export type WorkspaceDomain = "generic";

export function normalizeWorkspaceDomain(
  _input: string | null | undefined
): WorkspaceDomain {
  return "generic";
}

export function workspaceFooterLabel(_domain: WorkspaceDomain): string {
  return "Generated by Meeting AI Visualizer";
}

export function brandNameForDomain(_domain: WorkspaceDomain): string {
  return "the organization";
}

/** No-op — kept for call-site compatibility during migration. */
export function adaptSystemPromptForDomain(
  prompt: string,
  _domain: WorkspaceDomain
): string {
  return prompt;
}

/** No-op — kept for call-site compatibility during migration. */
export function adaptAuxiliarySystemPrompt(
  template: string,
  _domain: WorkspaceDomain
): string {
  return template;
}
