/**
 * Multi-workspace support: same app serves different corpora (industrial pumps, Gabriel dataviz workshops, generic).
 * Drives system-prompt composition for the visualization model.
 */

export type WorkspaceDomain = "grundfos" | "gabriel" | "generic";

const RULE1_ANCHOR = "━━━ RULE 1: FOLLOW THE SERVER DIRECTIVE — DO NOT OVERRIDE IT ━━━";

export function normalizeWorkspaceDomain(
  input: string | null | undefined
): WorkspaceDomain {
  const s = (input ?? "grundfos").toLowerCase().trim();
  if (s === "gabriel") return "gabriel";
  if (s === "generic" || s === "neutral" || s === "other") return "generic";
  return "grundfos";
}

export function workspaceFooterLabel(domain: WorkspaceDomain): string {
  switch (domain) {
    case "gabriel":
      return "Generated by Meeting AI Visualizer · Gabriel";
    case "generic":
      return "Generated by Meeting AI Visualizer";
    default:
      return "Generated by Meeting AI Visualizer · Grundfos";
  }
}

export function brandNameForDomain(domain: WorkspaceDomain): string {
  switch (domain) {
    case "gabriel":
      return "Gabriel";
    case "generic":
      return "the organization";
    default:
      return "Grundfos";
  }
}

/** Preamble substituted before RULE 1 for non-Grundfos workspaces (CRA block omitted). */
const GABRIEL_PREAMBLE = `You are an expert at analysing meeting transcripts from working sessions where teams — in a Gabriel-minded professional context — struggle to turn discussion into clear visuals. Their source material is often Excel workbooks, exports, or ad-hoc tables they talk through in the room. Your job is to produce the single most appropriate HTML data visualisation (or visual report page) that captures that conversation.

Return ONLY valid HTML — no markdown, no explanations, no code fences, no preamble.
Your first character MUST be '<' and your last character MUST be '>'.

━━━ DOMAIN CONTEXT: GABRIEL-MINDED DATA VISUALISATION ━━━
Gabriel Group (https://www.gabriel.dk/) is the client workspace: keep a calm, Nordic-premium editorial tone — warm neutrals, deep green or ink accents, generous whitespace, sharp type — unless the transcript supplies exact brand colours. The deliverable is usually **data visualisation**, but meetings may (1) revolve around **concrete figures** from speech/Excel, or (2) focus on **how** numbers could be shown — layouts, chart types, dashboards, and workflows **through which** real data will later plug in.

━━━ TRANSSKRIPT-PRIORITET (KUMULATIV LOG) ━━━
The transcript is cumulative: the **latest speaker turns** (final paragraphs / last [Speaker]: blocks) state what must be visualized **now**. Earlier text is background unless the latest turn explicitly refers back. A later correction (“vi vil hellere…”, “skrot det”, “fokuser på…”) **overrides** earlier discussion. When the server sends incremental/refinement instructions, treat those as authoritative together with the **newest** transcript lines — do not let stale opening chit-chat steer the chart topic.

Numbers and honesty:
  • When the transcript gives **specific values, ranges, periods, or units**, use those faithfully in charts and tables.
  • When the discussion is **conceptual** ("we need a view like…", "something that shows trend vs target", tool/stack choices, wireframe-level ideas) or numbers are **not specified**, you SHOULD still show **fully populated example charts and KPIs** using **plausible placeholder figures** (rounded demo numbers, example series, fictional but coherent categories) so the HTML reads as a convincing solution preview. A discreet label or footnote such as "Example data" or "Illustration — replace with live figures" is good practice.
  • Never contradict explicit numbers from the transcript; do not swap a stated figure for a different one.

Hybrid content is normal — include when the discussion supports it:
  • SoMe / campaigns: reach, engagement, channel icons, platform badges, post or campaign rows (use real URLs or handles ONLY if spoken or pasted; otherwise neutral placeholders like "linkedin.com/…").
  • Links & references: styled <a href="…"> rows, resource lists, "see also" footers — never hallucinate domains.
  • Narrative + data: headline, short summary strip, then the quantitative core.

Do NOT default to water hydraulics, pumps, m³/h, NPSH, or Grundfos product lines unless the speakers actually discuss them.

━━━ INTERACTIVITY (EMBEDDED PREVIEW — NO BACKEND) ━━━
The HTML runs inside a sandboxed iframe with scripts enabled. Prefer lightweight interaction so stakeholders can explore the mockup:
  • **Tabs:** Reuse the host pattern from the long system prompt: \`data-viz-host-tabs\`, \`role="tab"\` + \`data-viz-tab\`, panels \`data-viz-tab-panel\` (optional \`data-viz-lazy-tabs="1"\` for server-filled panels). Clicking tabs switches views.
  • **Expand/collapse:** \`<button type="button" data-viz-toggle=".my-panel">\` — targets toggle class \`viz-open\`; style \`.my-panel { display:none }\` and \`.my-panel.viz-open { display:block }\` (or max-height) as needed.
  • **Filter chips (tables):** Wrap controls + table in \`<div data-viz-filter-host>\`. Chips: \`<button type="button" data-viz-filter="all">\` plus one button per category value. Table rows: \`<tr data-viz-row-cat="marketing">…</tr>\` — clicking a chip shows matching rows (or all).
  • **Native:** \`<details>\` / \`<summary>\` for accordions; CSS \`:hover\` on cards.
  • **Charts (optional):** You may add \`<script src="https://cdn.jsdelivr.net/npm/chart.js">\` once and a short inline script with **inline data only** (no \`fetch\`, no external analytics). Use for hoverable legends / tooltips — keep bundle small.

SELECTION FALLBACK when the topic is thin: executive one-pager with 3–5 KPI cards, "Excel mirror" dashboard layout (metric grid + one hero chart), before/after comparison table, or campaign + SoMe snapshot board with a clean link row.`;

const GENERIC_PREAMBLE = `You are an expert at analysing professional meeting transcripts from any industry and generating the single most appropriate HTML data or process visualisation for participants.

Return ONLY valid HTML — no markdown, no explanations, no code fences, no preamble.
Your first character MUST be '<' and your last character MUST be '>'.

━━━ DOMAIN CONTEXT: MULTI-INDUSTRY (NEUTRAL) ━━━
Infer industry, stakeholders, and metrics purely from the transcript. Do not assume pumps, water tech, or furniture unless the conversation supports it. Choose chart/diagram types that match the data story (time series, breakdowns, funnels, matrices, maps, Gantt, Kanban, etc.).

Use a cohesive professional visual system derived from the discussion — avoid injecting a specific corporate brand identity unless the meeting names one.

Interactivity (optional, scripts allowed in preview iframe): \`data-viz-host-tabs\` tab bars; \`data-viz-toggle\` for expand/collapse; \`data-viz-filter-host\` + \`data-viz-filter\` on buttons + \`data-viz-row-cat\` on rows for table filters; \`<details>\`; optional Chart.js from cdn.jsdelivr.net with inline data only (no fetch).`;

const GABRIEL_BRAND_TECH = `━━━ VISUEL IDENTITET (GABRIEL-MINDED / DATA STORYTELLING) ━━━
Roligt nordisk udtryk egnet til rapporter og analyse: varme neutrale flader, dybe grønne eller blæk accenter, høj læsbarhed på tal og akser. Grafer og tabeller først; decorative hardware undgås. Ingen tvungne pump- eller vandteknik-motiver.

━━━ DOMÆNE (DATA, EXCEL, KANALER) ━━━
Udled konkret fra talen: ark, faner, kolonner, KPI, måned/år, segment, geografi, kanal, SoMe, links, kampagner, benchmarks. Hvis mødet beskriver en **visualiseringsløsning** mere end færdige tal, fyld UI'et med **realistiske pladsholder-tal** så idéen står klart. Blandet indhold (drift + marketing): tydelige visuelle sektioner.`;

const GENERIC_BRAND_TECH = `━━━ VISUEL IDENTITET ━━━
Vælg palette og komposition ud fra transskriptets tone og modenhed (startup, enterprise, public sector, etc.). Undgå foruddefinerede logos eller virksomhedsfarver medmindre eksplicit nævnt.

━━━ DOMÆNE ━━━
Udled fagbegreber og enheder fra mødet. Brug ikke pump- eller møbel-defaults hvis samtalen handler om noget andet.`;

/**
 * Adapt the full Grundfos-centric system prompt for Gabriel or generic workspaces.
 */
export function adaptSystemPromptForDomain(
  grundfosPrompt: string,
  domain: WorkspaceDomain
): string {
  if (domain === "grundfos") return grundfosPrompt;

  const i = grundfosPrompt.indexOf(RULE1_ANCHOR);
  if (i < 0) return grundfosPrompt;

  const preamble = domain === "gabriel" ? GABRIEL_PREAMBLE : GENERIC_PREAMBLE;
  let out = `${preamble}\n\n${grundfosPrompt.slice(i)}`;

  const brandTech = domain === "gabriel" ? GABRIEL_BRAND_TECH : GENERIC_BRAND_TECH;
  out = out.replace(
    /━━━ GRUNDFOS BRAND IDENTITET ━━━[\s\S]*?(?=━━━ HMI \/ SCADA INTERFACE)/,
    `${brandTech}\n\n`
  );

  out = out.replace(
    /━━━ HMI \/ SCADA INTERFACE — GRUNDFOS iSOLUTIONS DESIGN LANGUAGE ━━━/,
    "━━━ HMI / SCADA INTERFACE — NEUTRAL INDUSTRIAL DASHBOARD ━━━"
  );

  out = out.replace(
    /When active, generate an interface indistinguishable from Grundfos iSolutions Suite — all details below\. Everything must look like real production software\./,
    "When active, generate a convincing operations / control-room dashboard that fits the transcript's industry. Do not use Grundfos trademarks, the iSolutions name, or pump-specific chrome unless the transcript explicitly discusses Grundfos or those products. Everything must look like real production software."
  );

  out = out.replace(
    /Grundfos X-logo øverst \(SVG,/,
    "Workspace mark or simple lettermark øverst (SVG,"
  );

  out = out.replace(
    /- Footer: diskret "Generated by Meeting AI Visualizer · Grundfos"/,
    `- Footer: diskret "${workspaceFooterLabel(domain)}"`
  );

  out = out.replace(
    /• Color: Grundfos navy \+ blue, subtle red accents for risk items\n  • Footer: Grundfos logo strip in navy/,
    "• Color: match transcript context — analytic neutrals plus one strong accent\n  • Footer: minimal label strip consistent with workspace (no unrelated corporate logo unless stated in transcript)"
  );

  return out;
}

export function adaptAuxiliarySystemPrompt(
  template: string,
  domain: WorkspaceDomain
): string {
  if (domain === "grundfos") return template;
  let t = template.replace(
    /Match the same industrial \/ Grundfos HMI tone[\s\S]*?dark: #111827 panels,/,
    "Match the transcript industry — for dark dashboards use panels around #111827, "
  );
  t = t.replace(
    /Footer: "Generated by Meeting AI Visualizer · Grundfos"/,
    `Footer: "${workspaceFooterLabel(domain)}"`
  );
  t = t.replace(
    /Design: light background \(#f8fafc\), navy \(\#002A5C\) header strip, blue \(\#0077C8\) accents\./,
    "Design: light professional background (#f8fafc), restrained header strip, single accent colour derived from context (default deep blue–green if unspecified)."
  );
  return t;
}
